[package]
name = "holo-auth-client"
edition = "2018"
version = "0.0.0"

[dependencies]
ed25519-dalek = { version = "1.0.0-pre.1", features = ["serde"] }
failure = "0.1.5"
reqwest = "0.9.11"
serde = { version = "1.0.89", features = ["derive"] }
serde_json = "1.0.39"

[dependencies.hpos-config-core]
git = "https://github.com/Holo-Host/hpos-config"
branch = "develop"

[dependencies.zerotier]
git = "https://github.com/transumption/zerotier-rust"
branch = "release"
