kind: pipeline
name: x86_64-linux

platform:
  os: linux
  arch: amd64

steps:
- name: deploy
  image: nixos/nix
  commands:
  - |
    nix-shell \
      --option substituters 'https://cache.holo.host/ https://cache.nixos.org/' \
      --option trusted-public-keys \
        'cache.holo.host-1:lNXIXtJgS9Iuw4Cu6X0HINLu9sTfcjEntnrgwMQIMcE=
         cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=' \
      --run 'cd server; wrangler publish'
  environment:
    CF_API_TOKEN:
      from_secret: cf_api_token

trigger:
  branch:
  - master
